#ifndef __TEXTURES_H
#define __TEXTURES_H

enum INTERNAL_TEXTURE {
    LOAD0_ICON = 0,
    LOAD1_ICON,
    LOAD2_ICON,
    LOAD3_ICON,
    LOAD4_ICON,
    LOAD5_ICON,
    LOAD6_ICON,
    LOAD7_ICON,
    BDM_ICON,
    USB_ICON,
    ILINK_ICON,
    MX4SIO_ICON,
    HDD_BD_ICON,
    HDD_ICON,
    ETH_ICON,
    APP_ICON,
    FAV_ICON,
    FAV_MARK,
    MMCE_ICON,
    INDEX_0,
    INDEX_1,
    INDEX_2,
    INDEX_3,
    INDEX_4,
    R3_ICON,
    LEFT_ICON,
    RIGHT_ICON,
    CROSS_ICON,
    TRIANGLE_ICON,
    CIRCLE_ICON,
    SQUARE_ICON,
    SELECT_ICON,
    START_ICON,
    UP_ICON,
    DOWN_ICON,
    SETTINGS_BG,
    INFO_BG,
    COVER_DEFAULT,
    APP_COVER_DEFAULT,
    DISC_DEFAULT,
    SCREEN_DEFAULT,
    ELF_FORMAT,
    HDL_FORMAT,
    ISO_FORMAT,
    ZSO_FORMAT,
    UL_FORMAT,
    APP_MEDIA,
    CD_MEDIA,
    DVD_MEDIA,
    ASPECT_STD,
    ASPECT_WIDE,
    ASPECT_WIDE1,
    ASPECT_WIDE2,
    REGION_PAL,
    REGION_NTSC,
    PADEMU_ON,
    PADEMU_OFF,
    GSM_ON,
    GSM_OFF,
    CHT_ON,
    CHT_OFF,
    RATING_0,
    RATING_1,
    RATING_2,
    RATING_3,
    RATING_4,
    RATING_5,
    LOGO_01,
    LOGO_02,
    LOGO_03,
    LOGO_04,
    LOGO_05,
    LOGO_06,
    LOGO_07,
    LOGO_08,
    LOGO_09,
    LOGO_10,
    LOGO_11,
    LOGO_12,
    LOGO_13,
    LOGO_14,
    LOGO_15,
    LOGO_16,
    LOGO_17,
    LOGO_18,
    LOGO_19,
    LOGO_20,
    LOGO_21,
    CASE_OVERLAY,
    APPS_CASE_OVERLAY,
    PLANK,
    LM_CASE_OVERLAY,
    LM_APPS_CASE_OVERLAY,
    LM_CASE_SHADOW,

    TEXTURES_COUNT
};

#define ERR_BAD_FILE      -1
#define ERR_READ_STRUCT   -2
#define ERR_INFO_STRUCT   -3
#define ERR_SET_JMP       -4
#define ERR_BAD_DIMENSION -5
#define ERR_MISSING_ALPHA -6
#define ERR_BAD_DEPTH     -7

int texLookupInternalTexId(const char *name);
int texLoadInternal(GSTEXTURE *texture, int texId);
int texDiscoverLoad(GSTEXTURE *texture, const char *path, int texId, int archived);
void texFree(GSTEXTURE *texture);

#endif
