#ifndef __TEXTURES_H
#define __TEXTURES_H

enum INTERNAL_TEXTURE {
    LOADING_1_ICON = 0,
    LOADING_2_ICON,
    LOADING_3_ICON,
    LOADING_4_ICON,
    LOADING_5_ICON,
    LOADING_6_ICON,
    LOADING_7_ICON,
    LOADING_8_ICON,
    CATEGORY_EMPTY_BDM_ICON,
    CATEGORY_USB_ICON,
    CATEGORY_ILINK_ICON,
    CATEGORY_MX4SIO_ICON,
    CATEGORY_HDD_BDM_ICON,
    CATEGORY_HDD_APA_ICON,
    CATEGORY_NET_SMB_ICON,
    CATEGORY_APPS_ICON,
    CATEGORY_FAV_ICON,
    MARK_STAR,
    CATEGORY_MMCE_ICON,
    BDM_INDEX_1,
    BDM_INDEX_2,
    BDM_INDEX_3,
    BDM_INDEX_4,
    BDM_INDEX_5,
    BUTTON_STICK_R3_ICON,
    BUTTON_DPAD_LEFT_ICON,
    BUTTON_DPAD_RIGHT_ICON,
    BUTTON_SYMBOL_CROSS_ICON,
    BUTTON_SYMBOL_TRIANGLE_ICON,
    BUTTON_SYMBOL_CIRCLE_ICON,
    BUTTON_SYMBOL_SQUARE_ICON,
    BUTTON_SELECT_ICON,
    BUTTON_START_ICON,
    BUTTON_DPAD_UP_ICON,
    BUTTON_DPAD_DOWN_ICON,
    /* currently unused.
    L1_ICON,
    L2_ICON,
    L3_ICON,
    R1_ICON,
    R2_ICON, */
    BG_MAIN,
    BG_INFO,
    COVER_GAMES,
    COVER_APPS,
    DISC_DEFAULT,
    SCREENSHOT_DEFAULT,
    BADGE_EXEC_ELF_FORMAT,
    BADGE_DISC_HDL_FORMAT,
    BADGE_DISC_ISO_FORMAT,
    BADGE_DISC_ZSO_FORMAT,
    BADGE_DISC_UL_FORMAT,
    BADGE_EXEC_APP_MEDIA,
    BADGE_DISC_CD_MEDIA,
    BADGE_DISC_DVD_MEDIA,
    BADGE_VMODE_43,
    BADGE_VMODE_169,
    BADGE_VMODE_169_PS2RD,
    BADGE_VMODE_169_HEXISO,
    DEV_1,
    DEV_2,
    DEV_3,
    DEV_4,
    DEV_5,
    DEV_6,
    DEV_7,
    DEV_8,
    RATING_0,
    RATING_1,
    RATING_2,
    RATING_3,
    RATING_4,
    RATING_5,
    BADGE_RES_240P,
    BADGE_RES_240_HEXISO,
    BADGE_RES_480I,
    BADGE_RES_480P,
    BADGE_RES_480P_XT,
    BADGE_RES_480P_XC,
    BADGE_RES_480P_GSM,
    BADGE_RES_480P_PS2RD,
    BADGE_RES_480P_HEXISO,
    BADGE_RES_576I,
    BADGE_RES_576P_GSM,
    BADGE_RES_720P_GSM,
    BADGE_RES_1080I,
    BADGE_RES_1080I_GSM,
    BADGE_RES_1080P_GSM,
    BADGE_REGION_MULTI,
    BADGE_REGION_NTSC,
    BADGE_REGION_PAL,
    LOGO_PICTURE,
    CASE_OVERLAY,
    APPS_CASE_OVERLAY,
    PLANK,
    DISCBOX_LIST_GAMES_OVERLAY,
    DISCBOX_LIST_APPS_OVERLAY,
    DISCBOX_LIST_SHADOW_OVERLAY,

    TEXTURES_COUNT
};

#define ERR_BAD_FILE      -1
#define ERR_READ_STRUCT   -2
#define ERR_INFO_STRUCT   -3
#define ERR_SET_JMP       -4
#define ERR_BAD_DIMENSION -5
#define ERR_MISSING_ALPHA -6
#define ERR_BAD_DEPTH     -7

int texLookupInternalTexId(const char *name);
int texLoadInternal(GSTEXTURE *texture, int texId);
int texDiscoverLoad(GSTEXTURE *texture, const char *path, int texId, int archived);
void texFree(GSTEXTURE *texture);

#endif
